<?php
/**
 * ACF Fields Registration
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

// Add ACF Options Page
if (function_exists('acf_add_options_page')) {
    acf_add_options_page(array(
        'page_title' => 'Theme Settings',
        'menu_title' => 'Theme Settings',
        'menu_slug' => 'theme-settings',
        'capability' => 'edit_posts',
        'icon_url' => 'dashicons-admin-customizer',
    ));
}

// Add Header Tab with Logo Field
if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_header_settings',
        'title' => 'Header Settings',
        'fields' => array(
            array(
                'key' => 'field_header_tab',
                'label' => 'Header',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_logo',
                'label' => 'Logo',
                'name' => 'logo',
                'type' => 'image',
                'instructions' => 'Upload your site logo',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array(
                'key' => 'field_header_colour',
                'label' => 'Header Colour',
                'name' => 'header_colour',
                'type' => 'color_picker',
                'instructions' => 'Choose the header background colour',
                'default_value' => '#ffffff',
            ),
            array(
                'key' => 'field_left_menu',
                'label' => 'Left Menu',
                'name' => 'left_menu',
                'type' => 'repeater',
                'instructions' => 'Add menu items for the left side of header',
                'sub_fields' => array(
                    array(
                        'key' => 'field_left_menu_link',
                        'label' => 'Menu Link',
                        'name' => 'menu_link',
                        'type' => 'link',
                        'return_format' => 'array',
                    ),
                ),
                'min' => 0,
                'max' => 10,
                'layout' => 'table',
                'button_label' => 'Add Menu Item',
            ),
            array(
                'key' => 'field_right_menu',
                'label' => 'Right Menu',
                'name' => 'right_menu',
                'type' => 'repeater',
                'instructions' => 'Add menu items for the right side of header',
                'sub_fields' => array(
                    array(
                        'key' => 'field_right_menu_link',
                        'label' => 'Menu Link',
                        'name' => 'menu_link',
                        'type' => 'link',
                        'return_format' => 'array',
                    ),
                ),
                'min' => 0,
                'max' => 10,
                'layout' => 'table',
                'button_label' => 'Add Menu Item',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
    ));

    // Add Footer Tab
    // Update your existing Footer Settings ACF group with these fields:

    acf_add_local_field_group(array(
        'key' => 'group_footer_settings',
        'title' => 'Footer Settings',
        'fields' => array(
            array(
                'key' => 'field_footer_tab',
                'label' => 'Footer',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),

            // Hours Section
            array(
                'key' => 'field_hours_section',
                'label' => 'Hours Section',
                'name' => 'hours_section',
                'type' => 'group',
                'instructions' => 'Configure the hours section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_hours_title',
                        'label' => 'Hours Title',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Hours',
                    ),
                    array(
                        'key' => 'field_hours_subtitle',
                        'label' => 'Hours Subtitle',
                        'name' => 'subtitle',
                        'type' => 'text',
                        'default_value' => 'OPEN FOR INDOOR DINING',
                    ),
                    array(
                        'key' => 'field_hours_list',
                        'label' => 'Hours List',
                        'name' => 'hours_list',
                        'type' => 'repeater',
                        'instructions' => 'Add operating hours',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_day_time',
                                'label' => 'Day & Time',
                                'name' => 'day_time',
                                'type' => 'text',
                                'instructions' => 'e.g., Sunday – Thursday: 11:30am-2pm (lunch); 5-10pm (dinner)',
                            ),
                        ),
                        'min' => 1,
                        'max' => 10,
                        'layout' => 'table',
                        'button_label' => 'Add Hours',
                    ),
                ),
            ),

            // Dress Code Section
            array(
                'key' => 'field_dress_code_section',
                'label' => 'Dress Code Section',
                'name' => 'dress_code_section',
                'type' => 'group',
                'instructions' => 'Configure the dress code section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_dress_code_title',
                        'label' => 'Dress Code Title',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'DRESS CODE',
                    ),
                    array(
                        'key' => 'field_dress_code_content',
                        'label' => 'Dress Code Content',
                        'name' => 'content',
                        'type' => 'textarea',
                        'rows' => 3,
                        'default_value' => 'We politely request that you dress your best for your evening with us: Elegant for a NYC night out. Jackets are not required.',
                    ),
                ),
            ),

            // Contact Section
            array(
                'key' => 'field_contact_section',
                'label' => 'Contact Section',
                'name' => 'contact_section',
                'type' => 'group',
                'instructions' => 'Configure the contact section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_contact_title',
                        'label' => 'Contact Title',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Contact',
                    ),
                    array(
                        'key' => 'field_contact_items',
                        'label' => 'Contact Items',
                        'name' => 'contact_items',
                        'type' => 'repeater',
                        'instructions' => 'Add contact information',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_contact_label',
                                'label' => 'Label',
                                'name' => 'label',
                                'type' => 'text',
                                'instructions' => 'e.g., PHONE:, RESERVATIONS:, GENERAL:',
                            ),
                            array(
                                'key' => 'field_contact_value',
                                'label' => 'Value',
                                'name' => 'value',
                                'type' => 'text',
                                'instructions' => 'e.g., (212) 271-4252, email@domain.com',
                            ),
                            array(
                                'key' => 'field_contact_type',
                                'label' => 'Contact Type',
                                'name' => 'type',
                                'type' => 'select',
                                'choices' => array(
                                    'phone' => 'Phone',
                                    'email' => 'Email',
                                    'text' => 'Text',
                                ),
                                'default_value' => 'text',
                            ),
                        ),
                        'min' => 1,
                        'max' => 10,
                        'layout' => 'table',
                        'button_label' => 'Add Contact Item',
                    ),
                ),
            ),

            // Location Section
            array(
                'key' => 'field_location_section',
                'label' => 'Location Section',
                'name' => 'location_section',
                'type' => 'group',
                'instructions' => 'Configure the location section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_location_title',
                        'label' => 'Location Title',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Location',
                    ),
                    array(
                        'key' => 'field_address_line_1',
                        'label' => 'Address Line 1',
                        'name' => 'address_line_1',
                        'type' => 'text',
                        'default_value' => '138 Lafayette St.',
                    ),
                    array(
                        'key' => 'field_address_line_2',
                        'label' => 'Address Line 2',
                        'name' => 'address_line_2',
                        'type' => 'text',
                        'default_value' => 'New York, NY 10013',
                    ),
                ),
            ),

            // Connect With Us Section
            array(
                'key' => 'field_social_section',
                'label' => 'Connect With Us Section',
                'name' => 'social_section',
                'type' => 'group',
                'instructions' => 'Configure the social media section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_social_title',
                        'label' => 'Social Title',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Connect With Us',
                    ),
                    array(
                        'key' => 'field_social_links',
                        'label' => 'Social Links',
                        'name' => 'social_links',
                        'type' => 'repeater',
                        'instructions' => 'Add social media links',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_social_platform',
                                'label' => 'Platform Name',
                                'name' => 'platform',
                                'type' => 'text',
                                'instructions' => 'e.g., Facebook, Instagram, Spotify',
                            ),
                            array(
                                'key' => 'field_social_url',
                                'label' => 'URL',
                                'name' => 'url',
                                'type' => 'url',
                                'instructions' => 'Enter the full URL',
                            ),
                        ),
                        'min' => 1,
                        'max' => 10,
                        'layout' => 'table',
                        'button_label' => 'Add Social Link',
                    ),
                ),
            ),

            // Company Links Section
            array(
                'key' => 'field_company_section',
                'label' => 'Company Links Section',
                'name' => 'company_section',
                'type' => 'group',
                'instructions' => 'Configure the company links section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_company_title',
                        'label' => 'Company Title',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Starr Restaurants',
                    ),
                    array(
                        'key' => 'field_company_links_row_1',
                        'label' => 'Company Links Row 1',
                        'name' => 'company_links_row_1',
                        'type' => 'repeater',
                        'instructions' => 'Add first row of company links',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_company_link_1',
                                'label' => 'Link',
                                'name' => 'link',
                                'type' => 'link',
                                'return_format' => 'array',
                            ),
                        ),
                        'min' => 1,
                        'max' => 10,
                        'layout' => 'table',
                        'button_label' => 'Add Link',
                    ),
                    array(
                        'key' => 'field_company_links_row_2',
                        'label' => 'Company Links Row 2',
                        'name' => 'company_links_row_2',
                        'type' => 'repeater',
                        'instructions' => 'Add second row of company links',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_company_link_2',
                                'label' => 'Link',
                                'name' => 'link',
                                'type' => 'link',
                                'return_format' => 'array',
                            ),
                        ),
                        'min' => 1,
                        'max' => 10,
                        'layout' => 'table',
                        'button_label' => 'Add Link',
                    ),
                ),
            ),

            // Mailing List Section
            array(
                'key' => 'field_mailing_list_section',
                'label' => 'Mailing List Section',
                'name' => 'mailing_list_section',
                'type' => 'group',
                'instructions' => 'Configure the mailing list section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mailing_list_text',
                        'label' => 'Mailing List Text',
                        'name' => 'text',
                        'type' => 'text',
                        'default_value' => 'Join our Mailing List',
                    ),
                    array(
                        'key' => 'field_mailing_list_url',
                        'label' => 'Mailing List URL',
                        'name' => 'url',
                        'type' => 'url',
                        'instructions' => 'Enter the mailing list signup URL',
                    ),
                ),
            ),

            // Footer styling options
            array(
                'key' => 'field_footer_background_color',
                'label' => 'Footer Background Color',
                'name' => 'footer_background_color',
                'type' => 'color_picker',
                'instructions' => 'Choose the footer background color',
                'default_value' => '#f8f8f8',
            ),
            array(
                'key' => 'field_footer_text_color',
                'label' => 'Footer Text Color',
                'name' => 'footer_text_color',
                'type' => 'color_picker',
                'instructions' => 'Choose the footer text color',
                'default_value' => '#333333',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-settings',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
    ));

    // Add Page Builder Flexible Content
    acf_add_local_field_group(array(
        'key' => 'group_page_builder',
        'title' => 'Page Builder',
        'fields' => array(
            array(
                'key' => 'field_page_builder',
                'label' => 'Page Builder',
                'name' => 'page_builder',
                'type' => 'flexible_content',
                'instructions' => 'Add and arrange page components',
                'layouts' => array(
                    'layout_hero' => array(
                        'key' => 'layout_hero',
                        'name' => 'hero',
                        'label' => 'Hero Section',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_hero_image',
                                'label' => 'Hero Image',
                                'name' => 'hero_image',
                                'type' => 'image',
                                'instructions' => 'Upload the hero background image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_concept' => array(
                        'key' => 'layout_concept',
                        'name' => 'concept',
                        'label' => 'The Concept',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_concept_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => 'Enter the section title',
                            ),
                            array(
                                'key' => 'field_concept_content',
                                'label' => 'Content',
                                'name' => 'content',
                                'type' => 'wysiwyg',
                                'instructions' => 'Enter the section content',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array(
                                'key' => 'field_concept_image_1',
                                'label' => 'Image 1',
                                'name' => 'image_1',
                                'type' => 'image',
                                'instructions' => 'Upload the first image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array(
                                'key' => 'field_concept_image_2',
                                'label' => 'Image 2',
                                'name' => 'image_2',
                                'type' => 'image',
                                'instructions' => 'Upload the second image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array(
                                'key' => 'field_concept_image_3',
                                'label' => 'Image 3',
                                'name' => 'image_3',
                                'type' => 'image',
                                'instructions' => 'Upload the third image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array(
                                'key' => 'field_concept_border_radius',
                                'label' => 'Border Radius',
                                'name' => 'border_radius',
                                'type' => 'select',
                                'instructions' => 'Choose the border radius',
                                'choices' => array(
                                    '0' => '0px',
                                    '10' => '10px',
                                    '20' => '20px',
                                    '30' => '30px',
                                    '40' => '40px',
                                    '50' => '50px',
                                    '60' => '60px',
                                    '70' => '70px',
                                    '80' => '80px',
                                    '90' => '90px',
                                    '100' => '100px',
                                ),
                                'default_value' => '0',
                            ),
                            array(
                                'key' => 'field_concept_padding',
                                'label' => 'Padding',
                                'name' => 'padding',
                                'type' => 'select',
                                'instructions' => 'Choose the section padding',
                                'choices' => array(
                                    '0' => '0px',
                                    '20' => '20px',
                                    '40' => '40px',
                                    '60' => '60px',
                                    '80' => '80px',
                                    '100' => '100px',
                                    '120' => '120px',
                                    '140' => '140px',
                                    '160' => '160px',
                                    '180' => '180px',
                                    '200' => '200px',
                                ),
                                'default_value' => '40',
                            ),
                            array(
                                'key' => 'field_concept_background_color',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'instructions' => 'Choose the background color',
                                'default_value' => '#ffffff',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_spacer' => array(
                        'key' => 'layout_spacer',
                        'name' => 'spacer',
                        'label' => 'Spacer',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_spacer_desktop',
                                'label' => 'Desktop Spacing',
                                'name' => 'desktop',
                                'type' => 'select',
                                'instructions' => 'Choose desktop spacing',
                                'choices' => array(
                                    '0' => '0px',
                                    '20' => '20px',
                                    '40' => '40px',
                                    '60' => '60px',
                                    '80' => '80px',
                                    '100' => '100px',
                                    '120' => '120px',
                                    '140' => '140px',
                                    '160' => '160px',
                                    '180' => '180px',
                                    '200' => '200px',
                                ),
                                'default_value' => '40',
                            ),
                            array(
                                'key' => 'field_spacer_tablet',
                                'label' => 'Tablet Spacing',
                                'name' => 'tablet',
                                'type' => 'select',
                                'instructions' => 'Choose tablet spacing',
                                'choices' => array(
                                    '0' => '0px',
                                    '20' => '20px',
                                    '40' => '40px',
                                    '60' => '60px',
                                    '80' => '80px',
                                    '100' => '100px',
                                    '120' => '120px',
                                    '140' => '140px',
                                    '160' => '160px',
                                    '180' => '180px',
                                    '200' => '200px',
                                ),
                                'default_value' => '40',
                            ),
                            array(
                                'key' => 'field_spacer_mobile',
                                'label' => 'Mobile Spacing',
                                'name' => 'mobile',
                                'type' => 'select',
                                'instructions' => 'Choose mobile spacing',
                                'choices' => array(
                                    '0' => '0px',
                                    '20' => '20px',
                                    '40' => '40px',
                                    '60' => '60px',
                                    '80' => '80px',
                                    '100' => '100px',
                                    '120' => '120px',
                                    '140' => '140px',
                                    '160' => '160px',
                                    '180' => '180px',
                                    '200' => '200px',
                                ),
                                'default_value' => '20',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_cuisine' => array(
                        'key' => 'layout_cuisine',
                        'name' => 'cuisine',
                        'label' => 'Cuisine Block',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_cuisine_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => 'Enter the section title',
                            ),
                            array(
                                'key' => 'field_cuisine_content',
                                'label' => 'Content',
                                'name' => 'content',
                                'type' => 'wysiwyg',
                                'instructions' => 'Enter the section content',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array(
                                'key' => 'field_cuisine_image_1',
                                'label' => 'Image 1',
                                'name' => 'image_1',
                                'type' => 'image',
                                'instructions' => 'Upload the first image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array(
                                'key' => 'field_cuisine_image_2',
                                'label' => 'Image 2',
                                'name' => 'image_2',
                                'type' => 'image',
                                'instructions' => 'Upload the second image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array(
                                'key' => 'field_cuisine_border_radius',
                                'label' => 'Border Radius',
                                'name' => 'border_radius',
                                'type' => 'select',
                                'instructions' => 'Choose the border radius',
                                'choices' => array(
                                    '0' => '0px',
                                    '10' => '10px',
                                    '20' => '20px',
                                    '30' => '30px',
                                    '40' => '40px',
                                    '50' => '50px',
                                    '60' => '60px',
                                    '70' => '70px',
                                    '80' => '80px',
                                    '90' => '90px',
                                    '100' => '100px',
                                ),
                                'default_value' => '0',
                            ),
                            array(
                                'key' => 'field_cuisine_padding',
                                'label' => 'Padding',
                                'name' => 'padding',
                                'type' => 'select',
                                'instructions' => 'Choose the section padding',
                                'choices' => array(
                                    '0' => '0px',
                                    '20' => '20px',
                                    '40' => '40px',
                                    '60' => '60px',
                                    '80' => '80px',
                                    '100' => '100px',
                                    '120' => '120px',
                                    '140' => '140px',
                                    '160' => '160px',
                                    '180' => '180px',
                                    '200' => '200px',
                                ),
                                'default_value' => '40',
                            ),
                            array(
                                'key' => 'field_cuisine_background_color',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'instructions' => 'Choose the background color',
                                'default_value' => '#ffffff',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_chef' => array(
                        'key' => 'layout_chef',
                        'name' => 'chef',
                        'label' => 'Chef',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_chef_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => 'Enter the section title',
                            ),
                            array(
                                'key' => 'field_chef_content',
                                'label' => 'Content',
                                'name' => 'content',
                                'type' => 'wysiwyg',
                                'instructions' => 'Enter the section content',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array(
                                'key' => 'field_chef_image',
                                'label' => 'Chef Image',
                                'name' => 'chef_image',
                                'type' => 'image',
                                'instructions' => 'Upload the chef image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array(
                                'key' => 'field_chef_border_radius',
                                'label' => 'Border Radius',
                                'name' => 'border_radius',
                                'type' => 'select',
                                'instructions' => 'Choose the border radius',
                                'choices' => array(
                                    '0' => '0px',
                                    '10' => '10px',
                                    '20' => '20px',
                                    '30' => '30px',
                                    '40' => '40px',
                                    '50' => '50px',
                                    '60' => '60px',
                                    '70' => '70px',
                                    '80' => '80px',
                                    '90' => '90px',
                                    '100' => '100px',
                                ),
                                'default_value' => '0',
                            ),
                            array(
                                'key' => 'field_chef_padding',
                                'label' => 'Padding',
                                'name' => 'padding',
                                'type' => 'select',
                                'instructions' => 'Choose the section padding',
                                'choices' => array(
                                    '0' => '0px',
                                    '20' => '20px',
                                    '40' => '40px',
                                    '60' => '60px',
                                    '80' => '80px',
                                    '100' => '100px',
                                    '120' => '120px',
                                    '140' => '140px',
                                    '160' => '160px',
                                    '180' => '180px',
                                    '200' => '200px',
                                ),
                                'default_value' => '40',
                            ),
                            array(
                                'key' => 'field_chef_background_color',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'instructions' => 'Choose the background color',
                                'default_value' => '#ffffff',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_full_width_image' => array(
                        'key' => 'layout_full_width_image',
                        'name' => 'full_width_image',
                        'label' => 'Full Width Image',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_full_width_image',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => 'Upload the full width image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array(
                                'key' => 'field_full_width_border_radius',
                                'label' => 'Border Radius',
                                'name' => 'border_radius',
                                'type' => 'select',
                                'instructions' => 'Choose the border radius',
                                'choices' => array(
                                    '0' => '0px',
                                    '10' => '10px',
                                    '20' => '20px',
                                    '30' => '30px',
                                    '40' => '40px',
                                    '50' => '50px',
                                    '60' => '60px',
                                    '70' => '70px',
                                    '80' => '80px',
                                    '90' => '90px',
                                    '100' => '100px',
                                ),
                                'default_value' => '0',
                            ),
                            array(
                                'key' => 'field_full_width_padding',
                                'label' => 'Padding',
                                'name' => 'padding',
                                'type' => 'select',
                                'instructions' => 'Choose the section padding',
                                'choices' => array(
                                    '0' => '0px',
                                    '20' => '20px',
                                    '40' => '40px',
                                    '60' => '60px',
                                    '80' => '80px',
                                    '100' => '100px',
                                    '120' => '120px',
                                    '140' => '140px',
                                    '160' => '160px',
                                    '180' => '180px',
                                    '200' => '200px',
                                ),
                                'default_value' => '40',
                            ),
                            array(
                                'key' => 'field_full_width_background_color',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'instructions' => 'Choose the background color',
                                'default_value' => '#ffffff',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_menu' => array(
                        'key' => 'layout_menu',
                        'name' => 'menu',
                        'label' => 'Menu',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_menu_tabs',
                                'label' => 'Menu Tabs',
                                'name' => 'menu_tabs',
                                'type' => 'repeater',
                                'instructions' => 'Add menu tabs (e.g., Dinner, Lunch, Dessert, Beverage)',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_tab_name',
                                        'label' => 'Tab Name',
                                        'name' => 'tab_name',
                                        'type' => 'text',
                                        'instructions' => 'Enter tab name (e.g., DINNER, LUNCH)',
                                        'required' => 1,
                                    ),
                                    array(
                                        'key' => 'field_left_column_sections',
                                        'label' => 'Left Column Sections',
                                        'name' => 'left_column_sections',
                                        'type' => 'repeater',
                                        'instructions' => 'Add sections for left column',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_left_section_title',
                                                'label' => 'Section Title',
                                                'name' => 'section_title',
                                                'type' => 'text',
                                                'instructions' => 'Enter section title (e.g., Hors d\'oeuvres)',
                                            ),
                                            array(
                                                'key' => 'field_left_menu_items',
                                                'label' => 'Menu Items',
                                                'name' => 'menu_items',
                                                'type' => 'repeater',
                                                'instructions' => 'Add menu items for this section',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_left_item_title',
                                                        'label' => 'Item Title',
                                                        'name' => 'title',
                                                        'type' => 'text',
                                                        'instructions' => 'Enter menu item title',
                                                        'required' => 1,
                                                    ),
                                                    array(
                                                        'key' => 'field_left_item_ingredients',
                                                        'label' => 'Ingredients',
                                                        'name' => 'ingredients',
                                                        'type' => 'textarea',
                                                        'instructions' => 'Enter item ingredients/description',
                                                        'rows' => 2,
                                                    ),
                                                    array(
                                                        'key' => 'field_left_item_price',
                                                        'label' => 'Price',
                                                        'name' => 'price',
                                                        'type' => 'text',
                                                        'instructions' => 'Enter item price (numbers only)',
                                                    ),
                                                    array(
                                                        'key' => 'field_left_item_extras',
                                                        'label' => 'Extras',
                                                        'name' => 'extras',
                                                        'type' => 'repeater',
                                                        'instructions' => 'Add extra items/add-ons',
                                                        'sub_fields' => array(
                                                            array(
                                                                'key' => 'field_left_extra_ingredient',
                                                                'label' => 'Extra Ingredient',
                                                                'name' => 'ingredient',
                                                                'type' => 'text',
                                                                'instructions' => 'Enter extra ingredient (e.g., + caviar)',
                                                            ),
                                                            array(
                                                                'key' => 'field_left_extra_price',
                                                                'label' => 'Extra Price',
                                                                'name' => 'price',
                                                                'type' => 'text',
                                                                'instructions' => 'Enter extra price (numbers only)',
                                                            ),
                                                        ),
                                                        'min' => 0,
                                                        'max' => 10,
                                                        'layout' => 'table',
                                                        'button_label' => 'Add Extra',
                                                    ),
                                                ),
                                                'min' => 0,
                                                'max' => 20,
                                                'layout' => 'row',
                                                'button_label' => 'Add Menu Item',
                                            ),
                                        ),
                                        'min' => 0,
                                        'max' => 10,
                                        'layout' => 'row',
                                        'button_label' => 'Add Left Section',
                                    ),
                                    array(
                                        'key' => 'field_right_column_sections',
                                        'label' => 'Right Column Sections',
                                        'name' => 'right_column_sections',
                                        'type' => 'repeater',
                                        'instructions' => 'Add sections for right column',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_right_section_title',
                                                'label' => 'Section Title',
                                                'name' => 'section_title',
                                                'type' => 'text',
                                                'instructions' => 'Enter section title (e.g., Plats)',
                                            ),
                                            array(
                                                'key' => 'field_right_menu_items',
                                                'label' => 'Menu Items',
                                                'name' => 'menu_items',
                                                'type' => 'repeater',
                                                'instructions' => 'Add menu items for this section',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_right_item_title',
                                                        'label' => 'Item Title',
                                                        'name' => 'title',
                                                        'type' => 'text',
                                                        'instructions' => 'Enter menu item title',
                                                        'required' => 1,
                                                    ),
                                                    array(
                                                        'key' => 'field_right_item_ingredients',
                                                        'label' => 'Ingredients',
                                                        'name' => 'ingredients',
                                                        'type' => 'textarea',
                                                        'instructions' => 'Enter item ingredients/description',
                                                        'rows' => 2,
                                                    ),
                                                    array(
                                                        'key' => 'field_right_item_price',
                                                        'label' => 'Price',
                                                        'name' => 'price',
                                                        'type' => 'text',
                                                        'instructions' => 'Enter item price (numbers only)',
                                                    ),
                                                    array(
                                                        'key' => 'field_right_item_extras',
                                                        'label' => 'Extras',
                                                        'name' => 'extras',
                                                        'type' => 'repeater',
                                                        'instructions' => 'Add extra items/add-ons',
                                                        'sub_fields' => array(
                                                            array(
                                                                'key' => 'field_right_extra_ingredient',
                                                                'label' => 'Extra Ingredient',
                                                                'name' => 'ingredient',
                                                                'type' => 'text',
                                                                'instructions' => 'Enter extra ingredient (e.g., + caviar)',
                                                            ),
                                                            array(
                                                                'key' => 'field_right_extra_price',
                                                                'label' => 'Extra Price',
                                                                'name' => 'price',
                                                                'type' => 'text',
                                                                'instructions' => 'Enter extra price (numbers only)',
                                                            ),
                                                        ),
                                                        'min' => 0,
                                                        'max' => 10,
                                                        'layout' => 'table',
                                                        'button_label' => 'Add Extra',
                                                    ),
                                                ),
                                                'min' => 0,
                                                'max' => 20,
                                                'layout' => 'row',
                                                'button_label' => 'Add Menu Item',
                                            ),
                                        ),
                                        'min' => 0,
                                        'max' => 10,
                                        'layout' => 'row',
                                        'button_label' => 'Add Right Section',
                                    ),
                                ),
                                'min' => 1,
                                'max' => 10,
                                'layout' => 'row',
                                'button_label' => 'Add Menu Tab',
                            ),
                            array(
                                'key' => 'field_menu_padding',
                                'label' => 'Padding',
                                'name' => 'padding',
                                'type' => 'select',
                                'instructions' => 'Choose the section padding',
                                'choices' => array(
                                    '0' => '0px',
                                    '20' => '20px',
                                    '40' => '40px',
                                    '60' => '60px',
                                    '80' => '80px',
                                    '100' => '100px',
                                    '120' => '120px',
                                    '140' => '140px',
                                    '160' => '160px',
                                    '180' => '180px',
                                    '200' => '200px',
                                ),
                                'default_value' => '40',
                            ),
                            array(
                                'key' => 'field_menu_background_color',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'instructions' => 'Choose the background color',
                                'default_value' => '#ffffff',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'button_label' => 'Add Component',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
    ));
}
